# This is a basic workflow to help you get started with Actions

name: DigitalOcean Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    type: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    input:
      releaseType:
      description: 'Where to release (staging or prod)?'
      require: true
      default: 'staging'
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
  
    # Deploy to Staging
  staging:
    if: github.event.input.releaseType == 'staging'
    name: Deploy to Staging
    environment:
      name: Staging
      url: http://68.183.225.142/
    need: [build]
    runs-on: ubuntu-latest
    # Add test line
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy to DigitalOcean
        uses: actions/checkout@v2
        with:
          host: ${{secrets.SSH_HOST}} #IP address of the server
          key: ${{secrets.SSH_KEY}} #Public key of the server
          username: ${{ secrets.SSH_USERNAME}} #User of the server

          script: |
            mkdir html
            cd html
            git clone git@github.com:quyennguyenthanh/InstallWordPressOnDockerDesktop.git
            cd InstallWordPressOnDockerDesktop
            docker-compose up -d
